In [1]:
import pandas as pd
df = pd.read_csv("zomato_data.csv")
df

id delivery_person_id  ...           city  time_taken_min
0      0xcdcd      DEHRES17DEL01  ...  metropolitian              46
1      0xd987      KOCRES16DEL01  ...  metropolitian              23
2      0x2784     PUNERES13DEL03  ...  metropolitian              21
3      0xc8b6     LUDHRES15DEL02  ...  metropolitian              20
4      0xdb64      KNPRES14DEL02  ...  metropolitian              41
...       ...                ...  ...            ...             ...
41939  0x1178   RANCHIRES16DEL01  ...  metropolitian              33
41940  0x7c09      JAPRES04DEL01  ...  metropolitian              32
41941  0x4f8d     CHENRES08DEL03  ...  metropolitian              16
41942  0x5eee    COIMBRES11DEL01  ...  metropolitian              26
41943  0x5fb2   RANCHIRES09DEL02  ...  metropolitian              36

[41944 rows x 22 columns]

In [2]:
df.head()

id delivery_person_id  ...           city  time_taken_min
0  0xcdcd      DEHRES17DEL01  ...  metropolitian              46
1  0xd987      KOCRES16DEL01  ...  metropolitian              23
2  0x2784     PUNERES13DEL03  ...  metropolitian              21
3  0xc8b6     LUDHRES15DEL02  ...  metropolitian              20
4  0xdb64      KNPRES14DEL02  ...  metropolitian              41

[5 rows x 22 columns]

In [3]:
df.tail()

id delivery_person_id  ...           city  time_taken_min
41939  0x1178   RANCHIRES16DEL01  ...  metropolitian              33
41940  0x7c09      JAPRES04DEL01  ...  metropolitian              32
41941  0x4f8d     CHENRES08DEL03  ...  metropolitian              16
41942  0x5eee    COIMBRES11DEL01  ...  metropolitian              26
41943  0x5fb2   RANCHIRES09DEL02  ...  metropolitian              36

[5 rows x 22 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41944 entries, 0 to 41943
Data columns (total 22 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   id                           41944 non-null  object 
 1   delivery_person_id           41944 non-null  object 
 2   delivery_person_age          40225 non-null  float64
 3   delivery_person_ratings      40181 non-null  float64
 4   restaurant_latitude          41944 non-null  float64
 5   restaurant_longitude         41944 non-null  float64
 6   delivery_location_latitude   41944 non-null  float64
 7   delivery_location_longitude  41944 non-null  float64
 8   distance_km                  41944 non-null  float64
 9   order_date                   41944 non-null  object 
 10  order_datetime               36615 non-null  object 
 11  pickup_datetime              37340 non-null  object 
 12  pickup_to_delivery_min       32590 non-null  float64
 13  weather_conditio

In [5]:
df.shape

(41944, 22)

In [6]:
df.head()

id delivery_person_id  ...           city  time_taken_min
0  0xcdcd      DEHRES17DEL01  ...  metropolitian              46
1  0xd987      KOCRES16DEL01  ...  metropolitian              23
2  0x2784     PUNERES13DEL03  ...  metropolitian              21
3  0xc8b6     LUDHRES15DEL02  ...  metropolitian              20
4  0xdb64      KNPRES14DEL02  ...  metropolitian              41

[5 rows x 22 columns]

In [7]:
df.isnull().sum()

id                                0
delivery_person_id                0
delivery_person_age            1719
delivery_person_ratings        1763
restaurant_latitude               0
restaurant_longitude              0
delivery_location_latitude        0
delivery_location_longitude       0
distance_km                       0
order_date                        0
order_datetime                 5329
pickup_datetime                4604
pickup_to_delivery_min         9354
weather_conditions              569
road_traffic_density            555
vehicle_condition                 0
type_of_order                     0
type_of_vehicle                   0
multiple_deliveries             905
festival                        215
city                           1114
time_taken_min                    0
dtype: int64

In [8]:
df.dropna(inplace=True)

In [9]:
df.isnull().sum()

id                             0
delivery_person_id             0
delivery_person_age            0
delivery_person_ratings        0
restaurant_latitude            0
restaurant_longitude           0
delivery_location_latitude     0
delivery_location_longitude    0
distance_km                    0
order_date                     0
order_datetime                 0
pickup_datetime                0
pickup_to_delivery_min         0
weather_conditions             0
road_traffic_density           0
vehicle_condition              0
type_of_order                  0
type_of_vehicle                0
multiple_deliveries            0
festival                       0
city                           0
time_taken_min                 0
dtype: int64

In [10]:
df.shape

(30755, 22)

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.head()

id delivery_person_id  ...           city  time_taken_min
0  0xcdcd      DEHRES17DEL01  ...  metropolitian              46
1  0xd987      KOCRES16DEL01  ...  metropolitian              23
2  0x2784     PUNERES13DEL03  ...  metropolitian              21
3  0xc8b6     LUDHRES15DEL02  ...  metropolitian              20
4  0xdb64      KNPRES14DEL02  ...  metropolitian              41

[5 rows x 22 columns]

In [13]:
df.drop(['id','delivery_person_id'], axis=1, inplace=True)

In [14]:
df.head()

delivery_person_age  delivery_person_ratings  ...           city  time_taken_min
0                 36.0                      4.2  ...  metropolitian              46
1                 21.0                      4.7  ...  metropolitian              23
2                 23.0                      4.7  ...  metropolitian              21
3                 34.0                      4.3  ...  metropolitian              20
4                 24.0                      4.7  ...  metropolitian              41

[5 rows x 20 columns]

In [15]:
col = [
    'restaurant_latitude', 
    'restaurant_longitude', 
    'delivery_location_latitude', 
    'delivery_location_longitude'
    ]
df.drop(col, axis=1, inplace=True)

In [16]:
df.head()

delivery_person_age  delivery_person_ratings  ...           city time_taken_min
0                 36.0                      4.2  ...  metropolitian             46
1                 21.0                      4.7  ...  metropolitian             23
2                 23.0                      4.7  ...  metropolitian             21
3                 34.0                      4.3  ...  metropolitian             20
4                 24.0                      4.7  ...  metropolitian             41

[5 rows x 16 columns]

In [17]:
df.shape

(30755, 16)

In [18]:
col = ['order_date', 'order_datetime', 'pickup_datetime']
df.drop(col, axis=1, inplace=True)

In [19]:
df.shape

(30755, 13)

In [20]:
df.head()

delivery_person_age  delivery_person_ratings  ...           city  time_taken_min
0                 36.0                      4.2  ...  metropolitian              46
1                 21.0                      4.7  ...  metropolitian              23
2                 23.0                      4.7  ...  metropolitian              21
3                 34.0                      4.3  ...  metropolitian              20
4                 24.0                      4.7  ...  metropolitian              41

[5 rows x 13 columns]

In [21]:
df.weather_conditions = df.weather_conditions.astype("category")

In [22]:
df.head()

delivery_person_age  delivery_person_ratings  ...           city  time_taken_min
0                 36.0                      4.2  ...  metropolitian              46
1                 21.0                      4.7  ...  metropolitian              23
2                 23.0                      4.7  ...  metropolitian              21
3                 34.0                      4.3  ...  metropolitian              20
4                 24.0                      4.7  ...  metropolitian              41

[5 rows x 13 columns]

In [23]:
cols = ['weather_conditions', 'type_of_order', 'type_of_vehicle', 'city']
df = pd.get_dummies(df, columns=cols, dtype=int, drop_first=True)

In [24]:
df.head()

delivery_person_age  delivery_person_ratings  ...  city_semi-urban  city_urban
0                 36.0                      4.2  ...                0           0
1                 21.0                      4.7  ...                0           0
2                 23.0                      4.7  ...                0           0
3                 34.0                      4.3  ...                0           0
4                 24.0                      4.7  ...                0           0

[5 rows x 21 columns]

In [25]:
df.road_traffic_density.unique()

array(['jam', 'high', 'medium', 'low'], dtype=object)

In [26]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[['low','medium','high','jam']])
df.road_traffic_density = encoder.fit_transform(df[['road_traffic_density']])

In [27]:
df.road_traffic_density

0        3.0
1        2.0
2        1.0
3        0.0
4        3.0
        ... 
41937    1.0
41939    3.0
41940    2.0
41942    2.0
41943    1.0
Name: road_traffic_density, Length: 30755, dtype: float64

In [28]:
df.road_traffic_density

0        3.0
1        2.0
2        1.0
3        0.0
4        3.0
        ... 
41937    1.0
41939    3.0
41940    2.0
41942    2.0
41943    1.0
Name: road_traffic_density, Length: 30755, dtype: float64

In [29]:
df.head()

delivery_person_age  delivery_person_ratings  ...  city_semi-urban  city_urban
0                 36.0                      4.2  ...                0           0
1                 21.0                      4.7  ...                0           0
2                 23.0                      4.7  ...                0           0
3                 34.0                      4.3  ...                0           0
4                 24.0                      4.7  ...                0           0

[5 rows x 21 columns]

In [30]:
df.head()

delivery_person_age  delivery_person_ratings  ...  city_semi-urban  city_urban
0                 36.0                      4.2  ...                0           0
1                 21.0                      4.7  ...                0           0
2                 23.0                      4.7  ...                0           0
3                 34.0                      4.3  ...                0           0
4                 24.0                      4.7  ...                0           0

[5 rows x 21 columns]

In [31]:
dic = {
    "no":0,
    "yes":1
}
df.festival = df.festival.map(dic)

In [32]:
df.head()

delivery_person_age  delivery_person_ratings  ...  city_semi-urban  city_urban
0                 36.0                      4.2  ...                0           0
1                 21.0                      4.7  ...                0           0
2                 23.0                      4.7  ...                0           0
3                 34.0                      4.3  ...                0           0
4                 24.0                      4.7  ...                0           0

[5 rows x 21 columns]

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 30755 entries, 0 to 41943
Data columns (total 21 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   delivery_person_age            30755 non-null  float64
 1   delivery_person_ratings        30755 non-null  float64
 2   distance_km                    30755 non-null  float64
 3   pickup_to_delivery_min         30755 non-null  float64
 4   road_traffic_density           30755 non-null  float64
 5   vehicle_condition              30755 non-null  int64  
 6   multiple_deliveries            30755 non-null  float64
 7   festival                       30755 non-null  int64  
 8   time_taken_min                 30755 non-null  int64  
 9   weather_conditions_fog         30755 non-null  int64  
 10  weather_conditions_sandstorms  30755 non-null  int64  
 11  weather_conditions_stormy      30755 non-null  int64  
 12  weather_conditions_sunny       30755 non-null  int6

In [34]:
df.head()

delivery_person_age  delivery_person_ratings  ...  city_semi-urban  city_urban
0                 36.0                      4.2  ...                0           0
1                 21.0                      4.7  ...                0           0
2                 23.0                      4.7  ...                0           0
3                 34.0                      4.3  ...                0           0
4                 24.0                      4.7  ...                0           0

[5 rows x 21 columns]

In [35]:
df.columns

Index(['delivery_person_age', 'delivery_person_ratings', 'distance_km',
       'pickup_to_delivery_min', 'road_traffic_density', 'vehicle_condition',
       'multiple_deliveries', 'festival', 'time_taken_min',
       'weather_conditions_fog', 'weather_conditions_sandstorms',
       'weather_conditions_stormy', 'weather_conditions_sunny',
       'weather_conditions_windy', 'type_of_order_drinks',
       'type_of_order_meal', 'type_of_order_snack',
       'type_of_vehicle_motorcycle', 'type_of_vehicle_scooter',
       'city_semi-urban', 'city_urban'],
      dtype='object')

In [36]:
x = df.drop(['time_taken_min'], axis=1)
y = df.time_taken_min

In [37]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y)

In [38]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [39]:
y_pred = model.predict(x_test)
y_pred

array([13.36715331, 22.87025659, 16.2985264 , ..., 21.66082734,
       20.06954049, 26.46770117], shape=(7689,))

In [40]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

38.95844076165337

In [41]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

4.9902222283943845

In [42]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.5585573312568417

In [44]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor()
model.fit(x_train, y_train)

DecisionTreeRegressor()

In [45]:
y_pred = model.predict(x_test)
y_pred

array([19., 25., 26., ..., 18., 14., 29.], shape=(7689,))

In [48]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test, y_pred)

27.10261412407335

In [49]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_pred)

3.957601768760567

In [50]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.6928970955987714

In [51]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x_train, y_train)

RandomForestRegressor()

In [52]:
y_pred = model.predict(x_test)
y_pred

array([15.75, 31.34, 25.14, ..., 24.22, 16.74, 29.21], shape=(7689,))

In [53]:
mean_squared_error(y_test, y_pred)

15.375706073611653

In [54]:
mean_absolute_error(y_test, y_pred)

3.1182156327220705

In [55]:
r2_score(y_test, y_pred)

0.8257760682859151

In [56]:
from sklearn.svm import SVR
model = SVR()
model.fit(x_train, y_train)

SVR()

In [57]:
y_pred = model.predict(x_test)
y_pred

array([22.07361608, 26.65022468, 24.22823791, ..., 26.91437802,
       24.70178663, 26.0264344 ], shape=(7689,))

In [58]:
mean_squared_error(y_test, y_pred)

72.00361227642168

In [59]:
mean_absolute_error(y_test, y_pred)

6.81125140631628

In [60]:
r2_score(y_test, y_pred)

0.18411861098564475